### ISSUE TITLE
Pine64 port completely broken (missing libs, segfaults)

### ISSUE THREAD

**Issue by KaneRoot** [RaspBSD/raspbsd.github.io#1]
Hello,

I tried RaspBSD on a Pine64 and here my problems with it.

First, only one of the two images worked (FreeBSD-aarch64-12.0-GENERIC-308649M.img.gz). The other one didn't even launched the boot process on the Pine64.

Then, once the system booted, I tried to update : pkg update, pkg seemed to miss libarchive. I think this is a common problem, since there is pkg-static, so I launched pkg-static update and it worked (at least there were no apparent problems). Finally I installed tmux : pkg install tmux, and when I tried to run it : segfault. Few seconds after that the system completely crashed (I couldn't ping it anymore).

Is that expected? Do you run RaspBSD on a real hardware? Is the project abandoned?

Thanks!

**Comment by brd** [comment]
The http://download.raspbsd.org/FreeBSD-aarch64-12.0-GENERIC-312006M.img.gz img works well for me. Mine has a 60 day uptime, and has been doing well.

For pkg, a new img needs to be generated to catch up on some changes in HEAD.  I am attending EuroBSDCon though and will not be able to test a new image until after I return home.  I will try and build a new image, but would you be willing to test it before I get home?

**Comment by KaneRoot** [comment]
Yes, why not.

I really would like to have a router with packet filter on it. My pine64 may do it if I get a BSD running on it (and an USB<->ethernet adapter). So if I can help you in any way... let's do this! :-)

**Comment by KaneRoot** [comment]
Quick follow-up: I re-tried the http://download.raspbsd.org/FreeBSD-aarch64-12.0-GENERIC-312006M.img.gz image and this time it booted normally. This image came with the same problems than the other: impossible to install any application, update and pkg isn't running well (libarchive).

Besides that, I managed to get my USB <-> ethernet working! :-)

Waiting for you next build, hoping that updates will follow mainline freebsd binary updates (if possible).
